#!/bin/bash
# Run it with sudo

# Default installation set:
util_names=(move-volume move-db dmove-copy-id dmove-config dmove-nginx-proxy)

for item in ${util_names[*]}
do
    wget -nv https://raw.githubusercontent.com/pavelsr/dmove/master/$item -O /usr/local/bin/$item
    chmod +x /usr/local/bin/$item
done

dmove-config
dmove-copy-id
echo "Setup complete! Do not forget to dmove-copy-id if you updated config"
