#!/bin/bash
# Run it with sudo

read -e -p "Type default REMOTE_HOST like <login@ip.addr> for all dmove utils : " REMOTE_HOST
read -e -p "Type default REMOTE_FOLDER for all dmove utils : " REMOTE_FOLDER

cat <<EOF > ~/.dmove
REMOTE_HOST="$REMOTE_HOST"
REMOTE_FOLDER="$REMOTE_FOLDER"
EOF

# Default installation set:
set=(move-volume move-db dmove-copy-id dmove-config dmove-nginx-proxy)

for item in ${set[*]}
do
    wget https://raw.githubusercontent.com/pavelsr/dmove/master/$item -O /usr/local/bin/$item
    chmod +x /usr/local/bin/$item
done

ssh-copy-id $REMOTE_HOST
echo "Setup complete! Do not forget to dmove-copy-id if you updated config"
