#!/bin/bash

. ~/.dmove

CONTAINER=$1

if [ -z $CONTAINER ]; then
    echo -e "List of all running docker containers, sorted by name: "
    docker ps --format "{{.Names}}" | sort | column
    read -p "Type the name of container which you want to backup, default is $CONTAINER : " input
    CONTAINER=${input:-$CONTAINER}
fi

TMP_DIR='/tmp/dmove'
HOSTNAME=$(cat /etc/hostname)
TAG="$HOSTNAME/$CONTAINER"
read -p "Type the tag of container, default is $TAG : " input
TAG=${input:-$TAG}

IMAGE_ID=$(docker commit $CONTAINER $TAG-backup | cut -d: -f2)  # return 'sha256:...'
mkdir -p $TMP_DIR
docker save -o /tmp/dmove/$CONTAINER.tar $IMAGE_ID
echo "Container is transferring to $REMOTE_HOST:$TMP_DIR"
ssh $REMOTE_HOST "mkdir -p $TMP_DIR"
scp $TMP_DIR/$CONTAINER.tar $REMOTE_HOST:$TMP_DIR/$CONTAINER.tar
ssh $REMOTE_HOST "docker load -i $TMP_DIR/$CONTAINER.tar"
ssh $REMOTE_HOST "docker tag $IMAGE_ID $TAG"
