#!/bin/bash

. ~/.dmove

read -p "Type the name of container which you want to backup, default is $CONTAINER : " input
CONTAINER=${input:-$CONTAINER}

read -p "Type the remote host details, default is $REMOTE_HOST: " input
REMOTE_HOST=${input:-$REMOTE_HOST}

read -p "Specify full path to remote folder, where you want to copy volume data, default is $REMOTE_FOLDER: " input
REMOTE_FOLDER=${input:-$REMOTE_FOLDER}

for row in $(docker inspect $CONTAINER | jq -cr '.[].Mounts[].Source'); do
	echo "Working with volume ${row}"
	cd ${row}
	tar -zcvf $CONTAINER.tar.gz *
	ssh $REMOTE_HOST "mkdir -p $REMOTE_FOLDER"
	scp $CONTAINER.tar.gz $REMOTE_HOST:$REMOTE_FOLDER/..
	ssh $REMOTE_HOST "tar -xvf $REMOTE_FOLDER/../$CONTAINER.tar.gz -C $REMOTE_FOLDER"
done
